config/routes.rb
Rails.application.routes.draw do
  resources :stories

  resources :users

  resource :sessions, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/story.rb
class Story < ApplicationRecord
  validates_presence_of :title, :body

  # errors
  # { title: "can't be blank"}
end

app/models/user.rb
require "bcrypt"

class User < ApplicationRecord
  validates :email, uniqueness: true
  validates :email, :password, presence: true

  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_session

  helper_method :current_user

  def current_user
    return nil unless current_session
    User.find_by(id: current_session.user_id)
  end

  def current_session
    Session.find_by(session_id: session["user_session_id"])
  end

  protected

  def load_session
    session["init"] = true
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    Session.find_by(user_id: current_user.id).destroy
    session["user_session_id"] = nil

    redirect_to new_user_path
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  def index
    @stories = Story.all
  end

  def show
  end

  def new
    @story = Story.new
  end

  def edit
  end

  def create
    @story = Story.new(story_params)

    if @story.save
      redirect_to @story, notice: 'Story was successfully created.'
    else
      render "new"
    end
  end

  def update
    if @story.update(story_params)
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @story.destroy
    redirect_to stories_url, notice: 'Story was successfully destroyed.'
  end

  private
    def set_story
      @story = Story.find(params[:id])
    end

    def story_params
      params.require(:story).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      new_session = Session.create(user_id: @user.id, session_id: SecureRandom.hex)
      session["user_session_id"] = new_session.session_id

      redirect_to stories_path
    else
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.slim
html
  head
    title Hamster
    = csrf_meta_tags
    = csp_meta_tag

    link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    .container
      = yield

app/views/stories/_form.html.slim
= form_for story do |form|
  .field
    = form.label :title
    = form.text_field :title

  .field
    = form.label :body
    = form.text_area :body

  .actions
    = form.submit

app/views/stories/_story.html.slim
.story-container
  .story-title = story.title
  .story-body = truncate(story.body, length: 64)
  .story-actions
    => link_to 'See more', story
    => link_to 'Edit', edit_story_path(story)
    = link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.slim
.row
  .col-md-6.offset-md-3
    - if current_user
      strong> Signed in as #{current_user.email}
      = link_to "Sign out", sessions_path, method: :delete
.row
  .col-md-6.offset-md-3
    h1 Stories

    = render @stories

    br

    = link_to 'New Story', new_story_path

app/views/stories/new.html.slim
h1 New Story

= render 'form', story: @story

= link_to 'Back', stories_path

app/views/stories/show.html.slim
.row
  .col-md-6.offset-md-3
    hr
    h1 = @story.title

    p = @story.body

app/views/users/create.html.slim
h1 Hello, this is CREATE

app/views/users/new.html.slim
.row
  .col-md-6.offset-md-3
    h1 Sign up

    = form_for @user do |f|
      .form-group
        = f.text_field :email
      .form-group
        = f.password_field :password
      .form-group
        = f.submit